### ISSUE TITLE
What's the performance of GCN encoder ?

### ISSUE THREAD

**Issue by crazyofapple** [nusnlp/PtrNetDecoding4JERE#1]
Nice work. I have two questions, first "What's the performance of GCN encoder ?"; second "In dataset folder, it exist *.dep files with adj_mat information, Where are they from?"

**Comment by nayakt** [comment]
Thanks !!!!
We didn't see any improvement with GCN encoder, it was similar to LSTM encoder. 
adj_mat are obtained using spaCy and they are used with GCN encoder.

**Comment by crazyofapple** [comment]
Is it a syntactic structure tree or semantically dependent information? Or a self-constructed graph structure?

**Comment by nayakt** [comment]
adj_mat is dependency parse tree information of the sentences obtained using spaCy. Each inner array represents the dependency distance of the corresponding word from all other words in the sentence.

**Comment by crazyofapple** [comment]
Thank you !
