### ISSUE TITLE
Dimension of the outputs

### ISSUE THREAD

**Issue by BD-MF** [nusnlp/PtrNetDecoding4JERE#10]
at Line 887 of word_decoder.py ,the outputs' dimention is [batch_size*sequence_length , vocab_size], but the target's dimention is [batch_size, sequence_length]?  How to calculate the loss?

**Comment by nayakt** [comment]
target is resized to (batch_size * sequence_length) (line no 905). That is how NLLLoss of pytorch expects the input.

**Comment by BD-MF** [comment]
hank you very much for your prompt reply.

**Comment by BD-MF** [comment]
Thank you very much for your prompt reply.
