### ISSUE TITLE
help  error code

### ISSUE THREAD

**Issue by Zheydari** [nusnlp/PtrNetDecoding4JERE#11]
Hello, thank you for your beautiful article. I run the following error code when running. What is the cause and how can I fix it?
line 948, in <module>
    os.environ['CUDA_VISIBLE_DEVICES'] = sys.argv[1]

IndexError: list index out of range

**Comment by nayakt** [comment]
That is the gpu index. If you have multiple gpu, there are referred using integer indices as 0, 1, 2 like that. That argument decides which gpu will be used by the code.

**Comment by Zheydari** [comment]
[19:03, 6/21/2021] sadafjoon: sys.argv[0]
--> 948     random_seed = int(sys.argv[1])
    949     n_gpu = torch.cuda.device_count()
    950     set_random_seeds(random_seed)

ValueError: invalid literal for int() with base 10: '/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py'


I have two and I dialed 0 in line code 947, the next line is code 1, but it gives an error again

**Comment by nayakt** [comment]
Please follow the guidelines....you have to give the parameters in the command line.

**Comment by Zheydari** [comment]
I could not find the guidelines. Can you tell me where these files are?

**Comment by nayakt** [comment]
To run the ptrtnet_decoder.py use following command:

python3.5 ptrnet_decoder.py 0 1023 NYT29/ NYT29/ptrnet_decode_model train

0 is the gpu index
1023 is random_seed
NYT29/ is source data dir
NYT29/ptrnet_decode_model is target data dir
train is to train a model

Hope this solves your issue.
