### ISSUE TITLE
run error with recordclass module

### ISSUE THREAD

**Issue by AndDoIt** [nusnlp/PtrNetDecoding4JERE#13]
Thanks for your excellent work!
When I run the command with "python word_decoder.py 0 1023 NYT29/ NYT29/word_decode_model train", it has an error about recordclass module. Did you have this trouble before? The error output looks like this:

Traceback (most recent call last):
  File "word_decoder.py", line 10, in <module>
    from recordclass import recordclass
  File "/home/fintech/anaconda3/envs/py35/lib/python3.5/site-packages/recordclass/__init__.py", line 24, in <module>
    from .datatype import datatype, clsconfig
  File "/home/fintech/anaconda3/envs/py35/lib/python3.5/site-packages/recordclass/datatype.py", line 208
    return f'{typename}({args}, **{kw})'
                                       ^
SyntaxError: invalid syntax

**Comment by nayakt** [comment]
Thanks !!!
No, I didn't face this issue.

**Comment by s2drag0n** [comment]
> Thanks for your excellent work! When I run the command with "python word_decoder.py 0 1023 NYT29/ NYT29/word_decode_model train", it has an error about recordclass module. Did you have this trouble before? The error output looks like this:
> 
> Traceback (most recent call last): File "word_decoder.py", line 10, in from recordclass import recordclass File "/home/fintech/anaconda3/envs/py35/lib/python3.5/site-packages/recordclass/**init**.py", line 24, in from .datatype import datatype, clsconfig File "/home/fintech/anaconda3/envs/py35/lib/python3.5/site-packages/recordclass/datatype.py", line 208 return f'{typename}({args}, **{kw})' ^ SyntaxError: invalid syntax

Bro, I'm facing the same error. Have you solved it?
I knew it， just degrade the version of 
> recordclass 
to 0.11.0
