### ISSUE TITLE
Why the F1-score of HRL is 77.6?

### ISSUE THREAD

**Issue by gaikin** [nusnlp/PtrNetDecoding4JERE#2]
The performance of HRL can't achieve so high, 66.4 reported in original paper. 
Is the evaluation method not different from that paper?

**Comment by nayakt** [comment]
Hi,
The F1 score of 77.6 of HRL on NYT24 dataset. This dataset is the same NYT dataset used in CopyR paper (Extracting Relational Facts by an End-to-End Neural Model with Copy Mechanism). To the best of my knowledge, original HRL paper didn't report results on this dataset. 

We have used same evaluation method of HRL. You can check the score of original HRL paper and our run of HRL model on the NYT29 (mentioned as NYT10 in HRL paper) dataset. They are almost same.

Hope this clear your confusion.

Also, I could not find any F1 score of 66.4 in original HRL paper. 
Regards
Tapas

**Comment by gaikin** [comment]
I'm sorry, I didn't notice the version of dataset.
