### ISSUE TITLE
adj_mat

### ISSUE THREAD

**Issue by mrgjbd** [nusnlp/PtrNetDecoding4JERE#3]
Hi, how to get adj_mat?

**Comment by nayakt** [comment]
adj_mat is used only with GCN encoder. For NYT24 and NYT29 datasets, adj_mat is already included in the released datasets (.dep file).

adj_mat is dependency parse tree information of the sentences obtained using spaCy. Each inner array represents the dependency distance of the corresponding word from all other words in the sentence.

**Comment by mrgjbd** [comment]
thanks a lot
