### ISSUE TITLE
Have you tried 100d word embeddings?

### ISSUE THREAD

**Issue by gaikin** [nusnlp/PtrNetDecoding4JERE#5]
I wan to try with 100d word2vectors, but dont have NYT29 corpus. I tried other 100d embeddings, the performance was bad. Could you please support 100d NYT29 pre-trained word2vectors?

**Comment by nayakt** [comment]
I have shared the training/dev/test data of the NYT29 dataset at the following location. 

https://drive.google.com/drive/folders/1RPD9kuHUHp4O3gQLLD1CgDPigAlRiR7L?usp=sharing

You can train the word2vec model on the sentences of NYT29 corpus (.sent files) for 100d dimension vectors and use them. Hopefully it should work. But I didn't test my model with 100d vectors.

**Comment by nayakt** [comment]
NYT29 dataset is derived from the Riedel 2010 dataset which is available at the following location:

https://github.com/SharmisthaJat/RE-DS-Word-Attention-Models/blob/master/Data/Riedel2010/data.zip

You can use the sentences from this original location too to train word2vec 100d vectors.

**Comment by gaikin** [comment]
Ok, thanks.
