### ISSUE TITLE
About evaluation code

### ISSUE THREAD

**Issue by gaikin** [nusnlp/PtrNetDecoding4JERE#6]
I found that you calculated the performance of relation and entity generation in your paper. But the code you released seems doesn't contain this part. I think the methods you use are different from Zeng's(released), I want to know how to calculate them. Otherwise, will you release more detailed evaluation codes?

**Comment by nayakt** [comment]
We followed Takanobu et al. (2019) for evaluation. A tuple is considered correct if the entities (full entity names) and relation exactly match with a groud truth tuple. Then, calculate the F1 score.

**Comment by gaikin** [comment]
![image](https://user-images.githubusercontent.com/16111190/77134852-d68d0100-6aa3-11ea-986f-7187e61d6a68.png)

I want to know this part of calculation methods.

**Comment by nayakt** [comment]
Just consider the entities as a set and calculate the F1. Ignore the relations here.

For relations only consider the relations, ignore the entities.

**Comment by gaikin** [comment]
Ok, thanks.
