### ISSUE TITLE
About Table 2 ？

### ISSUE THREAD

**Issue by zlh-source** [nusnlp/PtrNetDecoding4JERE#8]
Hello,
The number of "Entity overlap type" I tested on NYT24 is inconsistent with the data you gave in "Table 2: Statistics of train/test split of the two datasets.". Could you please provide us with your test script? .

**Comment by nayakt** [comment]
In Table 2 the train split is basically the train and dev of the released dataset. So if you take the train and dev together from the released dataset, it should match with statistics given in Table 2.
