### ISSUE TITLE
About dev data ?

### ISSUE THREAD

**Issue by hhhOscar** [nusnlp/PtrNetDecoding4JERE#9]
Hi! 
I noticed that your train data is exactly the same as the one provided by Takanobu et al. (2019), but it seems you did not split the training data to generate dev data. So can you tell me where the dev data comes from? Thanks!

**Comment by nayakt** [comment]
I am assuming you are talking about the NYT29 dataset mentioned in my paper and this is referred as NYT10 in Takanobu et al. (2019). If you compare the NYT10 column of Table 1 in Takanobu et al. and NYT29 column of Table 2 in our paper you can the statistics are not same. I split the dataset of Takanobu et al to obtain the dev set.
Takanobu et al.: https://arxiv.org/pdf/1811.03925.pdf
Our paper: https://arxiv.org/pdf/1911.09886.pdf
